language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install Django==$DJANGO_VERSION
script:
  - pipenv run coverage run runtests.py && pipenv run coverage report
