language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  - DJANGO_VERSION=1.8.19
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.15
  - DJANGO_VERSION=2.0.8
  - DJANGO_VERSION=2.1
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install Django==$DJANGO_VERSION
script:
  - pipenv run coverage run runtests.py && pipenv run coverage report
