language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.9
  - DJANGO_VERSION=2.0.1
  - DJANGO_VERSION=2.0.2
  - DJANGO_VERSION=2.0.3
  - DJANGO_VERSION=2.0.4
install:
  - pip install -r requirements.txt
  - pip install Django==$DJANGO_VERSION
script:
  - python runtests.py
