dist: xenial
language: python
cache: pip

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

install:
  - pip install tox-travis

script:
  - tox

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      install:
        - pip install black pyflakes
      script:
        - pyflakes webmention tests
        - black --check webmention tests
