dist: xenial
language: python
cache: pip

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"

install:
  - pip install tox-travis

script:
  - tox

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script:
        - tox -e lint
