# Generated by Django 3.1.6 on 2021-04-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmention', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingWebmentionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('source_url', models.URLField(help_text='The URL on your server where this mention originates')),
                ('target_url', models.URLField(help_text='The URL that you mentioned.')),
                ('target_webmention_endpoint', models.URLField(blank=True, help_text='The endpoint URL to which we sent the webmention', null=True)),
                ('status_message', models.CharField(help_text='Success, or an explanation of what went wrong.', max_length=1024)),
                ('response_code', models.PositiveIntegerField(default=0)),
                ('successful', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Outgoing Webmention Statuses',
                'ordering': ['-created_at'],
            },
        ),
    ]
